language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - pip install -e .


script:
  - pytest 

script: pytest --cov=clickupy tests/

after_success:
  - coveralls